name: Build Controlplane
on:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

env:
  CI: true
  DO_NOT_TRACK: '1'

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-push-image
        with:
          docker_username: ${{secrets.DOCKER_USERNAME}}
          docker_password: ${{secrets.DOCKER_PASSWORD}}
          docker_context: .
          dockerfile: controlplane/Dockerfile
          token: ${{secrets.GITHUB_TOKEN}}
          image_name: controlplane
          image_description: "Cosmo Controlplane"
